"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.BADGES_SEED = void 0;
exports.BADGES_SEED = [
    // ── Logins & streaks ──────────────────────────────────
    {
        key: 'first-login',
        nameCs: 'Vítej!',
        nameEn: 'Welcome!',
        descriptionCs: 'Poprvé jsi se přihlásil do rodinného kalendáře.',
        descriptionEn: 'You logged in to the family calendar for the first time.',
        icon: '👋',
        category: 'Přihlášení',
        ruleType: 'FIRST',
        metric: 'LOGIN',
        threshold: 1,
        tier: 'BRONZE',
        sortOrder: 10,
    },
    {
        key: 'login-streak-3',
        nameCs: 'Vrácenec',
        nameEn: 'Returning visitor',
        descriptionCs: 'Přihlásil jsi se 3 dny v řadě. Dobrý zvyk!',
        descriptionEn: 'Logged in 3 days in a row. Good habit!',
        icon: '🔥',
        category: 'Přihlášení',
        ruleType: 'STREAK',
        metric: 'LOGIN',
        threshold: 3,
        tier: 'BRONZE',
        sortOrder: 11,
    },
    {
        key: 'login-streak-7',
        nameCs: 'Nepřehlédnutelný',
        nameEn: 'Can\'t miss me',
        descriptionCs: 'Celý týden v aplikaci každý den. Jsi hvězda!',
        descriptionEn: 'One full week logging in every day. You\'re a star!',
        icon: '⭐',
        category: 'Přihlášení',
        ruleType: 'STREAK',
        metric: 'LOGIN',
        threshold: 7,
        tier: 'SILVER',
        sortOrder: 12,
    },
    {
        key: 'login-streak-14',
        nameCs: 'Fanatik',
        nameEn: 'Fanatic',
        descriptionCs: 'Dva týdny bez přerušení. Ty nemáš volný den?',
        descriptionEn: 'Two weeks straight. Don\'t you take a day off?',
        icon: '💪',
        category: 'Přihlášení',
        ruleType: 'STREAK',
        metric: 'LOGIN',
        threshold: 14,
        tier: 'SILVER',
        sortOrder: 13,
    },
    {
        key: 'login-streak-30',
        nameCs: 'Kalendářový maniak',
        nameEn: 'Calendar maniac',
        descriptionCs: 'Měsíc přihlašování každý den. Vážně respekt!',
        descriptionEn: 'A full month of daily logins. Truly impressive!',
        icon: '🏆',
        category: 'Přihlášení',
        ruleType: 'STREAK',
        metric: 'LOGIN',
        threshold: 30,
        tier: 'GOLD',
        sortOrder: 14,
    },
    {
        key: 'login-streak-100',
        nameCs: 'Legenda',
        nameEn: 'Legend',
        descriptionCs: '100 dní v řadě. Ty jsi opravdová legenda rodinného plánovače.',
        descriptionEn: '100 days in a row. You are a true family planning legend.',
        icon: '👑',
        category: 'Přihlášení',
        ruleType: 'STREAK',
        metric: 'LOGIN',
        threshold: 100,
        tier: 'GOLD',
        sortOrder: 15,
    },
    {
        key: 'login-count-50',
        nameCs: 'Pravidelný návštěvník',
        nameEn: 'Regular visitor',
        descriptionCs: 'Celkem 50 přihlášení. Ty tu seš jako doma!',
        descriptionEn: 'Total of 50 logins. You\'re right at home here!',
        icon: '🏠',
        category: 'Přihlášení',
        ruleType: 'COUNT',
        metric: 'LOGIN',
        threshold: 50,
        tier: 'SILVER',
        sortOrder: 16,
    },
    {
        key: 'night-owl',
        nameCs: 'Noční sova',
        nameEn: 'Night owl',
        descriptionCs: 'Přihlásil ses po 22:00. Pozdní ptáče dál doskáče!',
        descriptionEn: 'Logged in after 10 PM. Night planning counts too!',
        icon: '🦉',
        category: 'Přihlášení',
        ruleType: 'SPECIAL',
        metric: 'LOGIN_AFTER_22',
        threshold: 1,
        tier: 'BRONZE',
        sortOrder: 17,
    },
    {
        key: 'early-bird',
        nameCs: 'Ranní ptáče',
        nameEn: 'Early bird',
        descriptionCs: 'Přihlásil ses před 6:00. Ráno moudrost rosí!',
        descriptionEn: 'Logged in before 6 AM. The early bird catches the worm!',
        icon: '🌅',
        category: 'Přihlášení',
        ruleType: 'SPECIAL',
        metric: 'LOGIN_BEFORE_6',
        threshold: 1,
        tier: 'BRONZE',
        sortOrder: 18,
    },
    {
        key: 'weekend-warrior',
        nameCs: 'Víkendový bojovník',
        nameEn: 'Weekend warrior',
        descriptionCs: 'Plánuješ i o víkendu? Chvályhodné!',
        descriptionEn: 'Planning on a weekend? Admirable!',
        icon: '📅',
        category: 'Přihlášení',
        ruleType: 'COUNT',
        metric: 'LOGIN_WEEKEND',
        threshold: 10,
        tier: 'BRONZE',
        sortOrder: 19,
    },
    // ── Event creation ────────────────────────────────────
    {
        key: 'first-event',
        nameCs: 'První čin',
        nameEn: 'First step',
        descriptionCs: 'Vytvořil jsi svou první událost v kalendáři!',
        descriptionEn: 'You created your first calendar event!',
        icon: '🎯',
        category: 'Události',
        ruleType: 'FIRST',
        metric: 'EVENT_CREATED',
        threshold: 1,
        tier: 'BRONZE',
        sortOrder: 20,
    },
    {
        key: 'event-count-10',
        nameCs: 'Plánovač',
        nameEn: 'Planner',
        descriptionCs: '10 událostí vytvořeno. Máš plán!',
        descriptionEn: '10 events created. You have a plan!',
        icon: '📋',
        category: 'Události',
        ruleType: 'COUNT',
        metric: 'EVENT_CREATED',
        threshold: 10,
        tier: 'BRONZE',
        sortOrder: 21,
    },
    {
        key: 'event-count-50',
        nameCs: 'Organizátor',
        nameEn: 'Organizer',
        descriptionCs: '50 událostí. Klobouk dolů před tvojí organizací!',
        descriptionEn: '50 events. Hats off to your organizational skills!',
        icon: '🗂️',
        category: 'Události',
        ruleType: 'COUNT',
        metric: 'EVENT_CREATED',
        threshold: 50,
        tier: 'SILVER',
        sortOrder: 22,
    },
    {
        key: 'event-count-100',
        nameCs: 'Mistr plánu',
        nameEn: 'Master planner',
        descriptionCs: '100 událostí! Jsi pravý mistr rodinné logistiky.',
        descriptionEn: '100 events! You are a true master of family logistics.',
        icon: '🧠',
        category: 'Události',
        ruleType: 'COUNT',
        metric: 'EVENT_CREATED',
        threshold: 100,
        tier: 'GOLD',
        sortOrder: 23,
    },
    {
        key: 'event-count-250',
        nameCs: 'Supersuperplán',
        nameEn: 'Superplanner',
        descriptionCs: '250 událostí. Vážně, máš život pěkně naplánovaný!',
        descriptionEn: '250 events. You really have life figured out!',
        icon: '🚀',
        category: 'Události',
        ruleType: 'COUNT',
        metric: 'EVENT_CREATED',
        threshold: 250,
        tier: 'GOLD',
        sortOrder: 24,
    },
    {
        key: 'first-recurring',
        nameCs: 'Rytmus',
        nameEn: 'Rhythm',
        descriptionCs: 'Nastavil jsi svou první opakující se událost. Pravidelnost je základ!',
        descriptionEn: 'You set up your first recurring event. Consistency is key!',
        icon: '🔄',
        category: 'Události',
        ruleType: 'FIRST',
        metric: 'RECURRING_EVENT_CREATED',
        threshold: 1,
        tier: 'BRONZE',
        sortOrder: 25,
    },
    {
        key: 'speedy-event',
        nameCs: 'Rychlík',
        nameEn: 'Speedy',
        descriptionCs: 'Událost vytvořena za méně než 30 sekund. Flash byl pomalý!',
        descriptionEn: 'Event created in under 30 seconds. The Flash would be jealous!',
        icon: '⚡',
        category: 'Události',
        ruleType: 'SPECIAL',
        metric: 'EVENT_CREATED_FAST',
        threshold: 1,
        tier: 'BRONZE',
        sortOrder: 26,
    },
    {
        key: 'prognostik',
        nameCs: 'Prognostik',
        nameEn: 'Forecaster',
        descriptionCs: 'Naplánoval jsi událost víc než 30 dní dopředu. Výhled do budoucna!',
        descriptionEn: 'Planned an event more than 30 days in advance. Looking ahead!',
        icon: '🔮',
        category: 'Události',
        ruleType: 'SPECIAL',
        metric: 'EVENT_PLANNED_30PLUS_DAYS',
        threshold: 1,
        tier: 'BRONZE',
        sortOrder: 27,
    },
    {
        key: 'feb-29',
        nameCs: 'Lovec přestupných let',
        nameEn: 'Leap year hunter',
        descriptionCs: 'Přidal jsi událost na 29. února. To se hned tak nepovede!',
        descriptionEn: 'You added an event on February 29th. That doesn\'t happen often!',
        icon: '📆',
        category: 'Události',
        ruleType: 'SPECIAL',
        metric: 'EVENT_ON_FEB29',
        threshold: 1,
        tier: 'GOLD',
        sortOrder: 28,
    },
    {
        key: 'event-with-attachment',
        nameCs: 'Dokladista',
        nameEn: 'Document keeper',
        descriptionCs: 'Přidal jsi přílohu k události. Vše doložené!',
        descriptionEn: 'You attached a file to an event. All documented!',
        icon: '📎',
        category: 'Události',
        ruleType: 'FIRST',
        metric: 'ATTACHMENT_UPLOADED',
        threshold: 1,
        tier: 'BRONZE',
        sortOrder: 29,
    },
    // ── Kid proposals ─────────────────────────────────────
    {
        key: 'first-proposal',
        nameCs: 'Odvážný návrh',
        nameEn: 'Bold proposal',
        descriptionCs: 'Podal jsi svůj první návrh události. Odvaha se cení!',
        descriptionEn: 'You submitted your first event proposal. Courage counts!',
        icon: '✋',
        category: 'Návrhy',
        ruleType: 'FIRST',
        metric: 'PROPOSAL_SUBMITTED',
        threshold: 1,
        tier: 'BRONZE',
        sortOrder: 30,
    },
    {
        key: 'first-approved-proposal',
        nameCs: 'Schváleno!',
        nameEn: 'Approved!',
        descriptionCs: 'Tvůj první návrh byl schválen. Skvělá argumentace!',
        descriptionEn: 'Your first proposal was approved. Great pitch!',
        icon: '✅',
        category: 'Návrhy',
        ruleType: 'FIRST',
        metric: 'PROPOSAL_APPROVED',
        threshold: 1,
        tier: 'BRONZE',
        sortOrder: 31,
    },
    {
        key: 'proposal-count-5',
        nameCs: 'Vyjednávač',
        nameEn: 'Negotiator',
        descriptionCs: '5 schválených návrhů. Ty umíš přesvědčit!',
        descriptionEn: '5 approved proposals. You know how to convince people!',
        icon: '🤝',
        category: 'Návrhy',
        ruleType: 'COUNT',
        metric: 'PROPOSAL_APPROVED',
        threshold: 5,
        tier: 'SILVER',
        sortOrder: 32,
    },
    {
        key: 'proposal-count-25',
        nameCs: 'Diplomat',
        nameEn: 'Diplomat',
        descriptionCs: '25 schválených návrhů. Jsi rodinný diplomat!',
        descriptionEn: '25 approved proposals. You\'re the family diplomat!',
        icon: '🎖️',
        category: 'Návrhy',
        ruleType: 'COUNT',
        metric: 'PROPOSAL_APPROVED',
        threshold: 25,
        tier: 'GOLD',
        sortOrder: 33,
    },
    {
        key: 'quick-approval',
        nameCs: 'Přesvědčovací talent',
        nameEn: 'Persuasion talent',
        descriptionCs: 'Tvůj návrh byl schválen do 10 minut. Jsi neodolatelný!',
        descriptionEn: 'Your proposal was approved within 10 minutes. You\'re irresistible!',
        icon: '🌟',
        category: 'Návrhy',
        ruleType: 'SPECIAL',
        metric: 'PROPOSAL_APPROVED_FAST',
        threshold: 1,
        tier: 'SILVER',
        sortOrder: 34,
    },
    {
        key: 'three-proposals-day',
        nameCs: 'Ambiciózní',
        nameEn: 'Ambitious',
        descriptionCs: '3 návrhy za jeden den. Víš čeho chceš!',
        descriptionEn: '3 proposals in one day. You know what you want!',
        icon: '💡',
        category: 'Návrhy',
        ruleType: 'SPECIAL',
        metric: 'THREE_PROPOSALS_ONE_DAY',
        threshold: 1,
        tier: 'BRONZE',
        sortOrder: 35,
    },
    // ── Hockey ────────────────────────────────────────────
    {
        key: 'first-hockey-training',
        nameCs: 'Na led!',
        nameEn: 'Hit the ice!',
        descriptionCs: 'První hokejový trénink v kalendáři. Ať táhne!',
        descriptionEn: 'First hockey training on the calendar. Let\'s go!',
        icon: '🏒',
        category: 'Hokej',
        ruleType: 'FIRST',
        metric: 'EVENT_CREATED_hokej-trening',
        threshold: 1,
        tier: 'BRONZE',
        sortOrder: 40,
    },
    {
        key: 'hockey-training-10',
        nameCs: 'Bruslař',
        nameEn: 'Skater',
        descriptionCs: '10 hokejových tréninků naplánováno. Puk drží!',
        descriptionEn: '10 hockey trainings planned. The puck is yours!',
        icon: '⛸️',
        category: 'Hokej',
        ruleType: 'COUNT',
        metric: 'EVENT_CREATED_hokej-trening',
        threshold: 10,
        tier: 'BRONZE',
        sortOrder: 41,
    },
    {
        key: 'hockey-training-50',
        nameCs: 'Hokejista',
        nameEn: 'Hockey player',
        descriptionCs: '50 hokejových tréninků. To je pořádná sezona!',
        descriptionEn: '50 hockey trainings. That\'s a full season!',
        icon: '🥅',
        category: 'Hokej',
        ruleType: 'COUNT',
        metric: 'EVENT_CREATED_hokej-trening',
        threshold: 50,
        tier: 'SILVER',
        sortOrder: 42,
    },
    {
        key: 'hockey-training-100',
        nameCs: 'NHL Draft Pick',
        nameEn: 'NHL Draft Pick',
        descriptionCs: '100 hokejových tréninků. Skauti z NHL volají!',
        descriptionEn: '100 hockey trainings. NHL scouts are calling!',
        icon: '🌟',
        category: 'Hokej',
        ruleType: 'COUNT',
        metric: 'EVENT_CREATED_hokej-trening',
        threshold: 100,
        tier: 'GOLD',
        sortOrder: 43,
    },
    {
        key: 'first-hockey-match',
        nameCs: 'Do boje!',
        nameEn: 'Game on!',
        descriptionCs: 'První zápas v kalendáři. Vyhrajte!',
        descriptionEn: 'First match on the calendar. Go win!',
        icon: '🏟️',
        category: 'Hokej',
        ruleType: 'FIRST',
        metric: 'EVENT_CREATED_hokej-zapas',
        threshold: 1,
        tier: 'BRONZE',
        sortOrder: 44,
    },
    {
        key: 'first-hockey-tournament',
        nameCs: 'Turnajový hrdina',
        nameEn: 'Tournament hero',
        descriptionCs: 'První turnaj v kalendáři. Dej do toho vše!',
        descriptionEn: 'First tournament on the calendar. Give it your all!',
        icon: '🏆',
        category: 'Hokej',
        ruleType: 'FIRST',
        metric: 'EVENT_CREATED_hokej-turnaj',
        threshold: 1,
        tier: 'SILVER',
        sortOrder: 45,
    },
    {
        key: 'hockey-streak-5',
        nameCs: 'Železný bruslař',
        nameEn: 'Iron skater',
        descriptionCs: '5 týdnů tréninků bez přerušení. Ty jsi z oceli!',
        descriptionEn: '5 weeks of training without a break. You\'re made of iron!',
        icon: '🔩',
        category: 'Hokej',
        ruleType: 'STREAK',
        metric: 'EVENT_CREATED_hokej-trening',
        threshold: 35,
        tier: 'GOLD',
        sortOrder: 46,
    },
    // ── Swimming ──────────────────────────────────────────
    {
        key: 'first-swim-training',
        nameCs: 'Do vody!',
        nameEn: 'Dive in!',
        descriptionCs: 'První plavecký trénink v kalendáři. Voda čeká!',
        descriptionEn: 'First swimming training on the calendar. The water awaits!',
        icon: '🏊',
        category: 'Plavání',
        ruleType: 'FIRST',
        metric: 'EVENT_CREATED_plavani-trening',
        threshold: 1,
        tier: 'BRONZE',
        sortOrder: 50,
    },
    {
        key: 'swim-training-10',
        nameCs: 'Šplouchanec',
        nameEn: 'Splasher',
        descriptionCs: '10 plaveckých tréninků. Bazén se bojí!',
        descriptionEn: '10 swim trainings. The pool is yours to conquer!',
        icon: '💦',
        category: 'Plavání',
        ruleType: 'COUNT',
        metric: 'EVENT_CREATED_plavani-trening',
        threshold: 10,
        tier: 'BRONZE',
        sortOrder: 51,
    },
    {
        key: 'swim-training-50',
        nameCs: 'Vodní raketa',
        nameEn: 'Water rocket',
        descriptionCs: '50 plaveckých tréninků. Faster than a fish!',
        descriptionEn: '50 swim trainings. Faster than a fish!',
        icon: '🐟',
        category: 'Plavání',
        ruleType: 'COUNT',
        metric: 'EVENT_CREATED_plavani-trening',
        threshold: 50,
        tier: 'SILVER',
        sortOrder: 52,
    },
    {
        key: 'swim-training-100',
        nameCs: 'Delfín',
        nameEn: 'Dolphin',
        descriptionCs: '100 plaveckých tréninků. Delfíni se bojí konkurence!',
        descriptionEn: '100 swim trainings. Dolphins are getting worried!',
        icon: '🐬',
        category: 'Plavání',
        ruleType: 'COUNT',
        metric: 'EVENT_CREATED_plavani-trening',
        threshold: 100,
        tier: 'GOLD',
        sortOrder: 53,
    },
    {
        key: 'first-swim-race',
        nameCs: 'Startovní blok',
        nameEn: 'On your marks',
        descriptionCs: 'První závody v kalendáři. Připrav se, pozor, teď!',
        descriptionEn: 'First race on the calendar. On your marks, get set, go!',
        icon: '🥊',
        category: 'Plavání',
        ruleType: 'FIRST',
        metric: 'EVENT_CREATED_plavani-zavody',
        threshold: 1,
        tier: 'SILVER',
        sortOrder: 54,
    },
    {
        key: 'swim-streak-5',
        nameCs: 'Bazénový fanatik',
        nameEn: 'Pool fanatic',
        descriptionCs: '5 týdnů plavání bez přerušení. Voda je tvůj element!',
        descriptionEn: '5 weeks of swimming without a break. Water is your element!',
        icon: '🌊',
        category: 'Plavání',
        ruleType: 'STREAK',
        metric: 'EVENT_CREATED_plavani-trening',
        threshold: 35,
        tier: 'GOLD',
        sortOrder: 55,
    },
    // ── School ────────────────────────────────────────────
    {
        key: 'first-test',
        nameCs: 'Pen a papír připraven',
        nameEn: 'Pen and paper ready',
        descriptionCs: 'První test naplánován. Trochu strachu nikdy neškodí!',
        descriptionEn: 'First test planned. A little nerves never hurt!',
        icon: '📝',
        category: 'Škola',
        ruleType: 'FIRST',
        metric: 'EVENT_CREATED_skola-test',
        threshold: 1,
        tier: 'BRONZE',
        sortOrder: 60,
    },
    {
        key: 'test-survivor-10',
        nameCs: 'Přeživší',
        nameEn: 'Survivor',
        descriptionCs: '10 testů přežito v kalendáři. Statečnost zaznamenána!',
        descriptionEn: '10 tests survived on the calendar. Bravery recorded!',
        icon: '🛡️',
        category: 'Škola',
        ruleType: 'COUNT',
        metric: 'EVENT_CREATED_skola-test',
        threshold: 10,
        tier: 'BRONZE',
        sortOrder: 61,
    },
    {
        key: 'test-survivor-50',
        nameCs: 'Veterán',
        nameEn: 'Veteran',
        descriptionCs: '50 testů. Diplom za přežití by ses měl dostat!',
        descriptionEn: '50 tests. You deserve a survival diploma!',
        icon: '🎓',
        category: 'Škola',
        ruleType: 'COUNT',
        metric: 'EVENT_CREATED_skola-test',
        threshold: 50,
        tier: 'SILVER',
        sortOrder: 62,
    },
    {
        key: 'full-week-schedule',
        nameCs: 'Rozvrh hotov',
        nameEn: 'Schedule done',
        descriptionCs: 'Celý týdenní rozvrh zadán do kalendáře. Přehled je základ!',
        descriptionEn: 'Full weekly schedule added to the calendar. Organization is everything!',
        icon: '📓',
        category: 'Škola',
        ruleType: 'SPECIAL',
        metric: 'FULL_WEEK_SCHOOL_SCHEDULE',
        threshold: 1,
        tier: 'SILVER',
        sortOrder: 63,
    },
    {
        key: 'first-school-trip',
        nameCs: 'Poznávám svět',
        nameEn: 'Exploring the world',
        descriptionCs: 'První školní výlet v kalendáři. Batohy balte!',
        descriptionEn: 'First school trip on the calendar. Pack your bags!',
        icon: '🚌',
        category: 'Škola',
        ruleType: 'FIRST',
        metric: 'EVENT_CREATED_skola-vylet',
        threshold: 1,
        tier: 'BRONZE',
        sortOrder: 64,
    },
    // ── Family & travel ───────────────────────────────────
    {
        key: 'first-family-trip',
        nameCs: 'Dobrodruzi',
        nameEn: 'Adventurers',
        descriptionCs: 'První rodinný výlet naplánován. Čekají vás dobrodružství!',
        descriptionEn: 'First family trip planned. Adventures await!',
        icon: '🗺️',
        category: 'Rodina',
        ruleType: 'FIRST',
        metric: 'EVENT_CREATED_rodina-vylet',
        threshold: 1,
        tier: 'BRONZE',
        sortOrder: 70,
    },
    {
        key: 'first-vacation',
        nameCs: 'Zasloužená dovolená',
        nameEn: 'Well-deserved vacation',
        descriptionCs: 'Dovolená naplánována! Nesmíte zapomenout opasek na kufr.',
        descriptionEn: 'Vacation planned! Don\'t forget the luggage belt.',
        icon: '🏖️',
        category: 'Rodina',
        ruleType: 'FIRST',
        metric: 'EVENT_CREATED_rodina-dovolena',
        threshold: 1,
        tier: 'BRONZE',
        sortOrder: 71,
    },
    {
        key: 'grandparents-stay',
        nameCs: 'U babičky',
        nameEn: 'At grandma\'s',
        descriptionCs: 'Pobyt u prarodičů naplánován. Těší se i babička!',
        descriptionEn: 'Stay at grandparents planned. Grandma is excited too!',
        icon: '🏡',
        category: 'Rodina',
        ruleType: 'FIRST',
        metric: 'EVENT_CREATED_rodina-babicka',
        threshold: 1,
        tier: 'BRONZE',
        sortOrder: 72,
    },
    {
        key: 'roadtrip-count-5',
        nameCs: 'Cestovatel',
        nameEn: 'Traveler',
        descriptionCs: '5 roadtripů. Na dálnice to znáte!',
        descriptionEn: '5 road trips. You know the highways well!',
        icon: '🚗',
        category: 'Rodina',
        ruleType: 'COUNT',
        metric: 'EVENT_CREATED_rodina-roadtrip',
        threshold: 5,
        tier: 'SILVER',
        sortOrder: 73,
    },
    {
        key: 'locations-10',
        nameCs: 'Globetrotter',
        nameEn: 'Globetrotter',
        descriptionCs: 'Navštívili jste 10 různých míst. Svět je váš!',
        descriptionEn: 'You\'ve visited 10 different locations. The world is yours!',
        icon: '🌍',
        category: 'Rodina',
        ruleType: 'SPECIAL',
        metric: 'UNIQUE_LOCATIONS_10',
        threshold: 10,
        tier: 'GOLD',
        sortOrder: 74,
    },
    {
        key: 'summer-camp-first',
        nameCs: 'Na tábor!',
        nameEn: 'Off to camp!',
        descriptionCs: 'První letní tábor naplánován. Barrák, vítej!',
        descriptionEn: 'First summer camp planned. Adventure awaits!',
        icon: '⛺',
        category: 'Rodina',
        ruleType: 'FIRST',
        metric: 'EVENT_CREATED_tabor-letni',
        threshold: 1,
        tier: 'BRONZE',
        sortOrder: 75,
    },
    // ── Guardians ─────────────────────────────────────────
    {
        key: 'first-availability',
        nameCs: 'K dispozici',
        nameEn: 'Available',
        descriptionCs: 'Poprvé jsi nastavil svou dostupnost. Rodina ví, na koho se spolehnout!',
        descriptionEn: 'You set your availability for the first time. The family knows who to count on!',
        icon: '📍',
        category: 'Strážci',
        ruleType: 'FIRST',
        metric: 'AVAILABILITY_SET',
        threshold: 1,
        tier: 'BRONZE',
        sortOrder: 80,
    },
    {
        key: 'availability-count-10',
        nameCs: 'Spolehlivý',
        nameEn: 'Reliable',
        descriptionCs: '10 záznamů dostupnosti. Jsi spolehlivý člen rodiny!',
        descriptionEn: '10 availability records. You\'re a reliable family member!',
        icon: '👍',
        category: 'Strážci',
        ruleType: 'COUNT',
        metric: 'AVAILABILITY_SET',
        threshold: 10,
        tier: 'BRONZE',
        sortOrder: 81,
    },
    {
        key: 'availability-count-50',
        nameCs: 'Záchranná síť',
        nameEn: 'Safety net',
        descriptionCs: '50 záznamů dostupnosti. Jsi záchranná síť celé rodiny!',
        descriptionEn: '50 availability records. You\'re the family\'s safety net!',
        icon: '🕸️',
        category: 'Strážci',
        ruleType: 'COUNT',
        metric: 'AVAILABILITY_SET',
        threshold: 50,
        tier: 'SILVER',
        sortOrder: 82,
    },
    {
        key: 'coverage-gap-filled',
        nameCs: 'Zachránce dne',
        nameEn: 'Day saver',
        descriptionCs: 'Zaplnil jsi den, kdy jinak nebylo hlídání! Hrdina!',
        descriptionEn: 'You covered a day that would have been uncovered! Hero!',
        icon: '🦸',
        category: 'Strážci',
        ruleType: 'SPECIAL',
        metric: 'COVERAGE_GAP_FILLED',
        threshold: 1,
        tier: 'GOLD',
        sortOrder: 83,
    },
    {
        key: 'grandparent-first-login',
        nameCs: 'Babička online',
        nameEn: 'Grandparent online',
        descriptionCs: 'Prarodič se přihlásil! Technika zvítězila!',
        descriptionEn: 'Grandparent logged in! Technology wins!',
        icon: '👴',
        category: 'Strážci',
        ruleType: 'SPECIAL',
        metric: 'GRANDPARENT_FIRST_LOGIN',
        threshold: 1,
        tier: 'SILVER',
        sortOrder: 84,
    },
    // ── Profile & app ─────────────────────────────────────
    {
        key: 'photo-uploaded',
        nameCs: 'Tvář rodiny',
        nameEn: 'Family face',
        descriptionCs: 'Nahral jsi svoji profilovou fotku. Teď tě poznáme!',
        descriptionEn: 'You uploaded your profile photo. Now we know who you are!',
        icon: '📸',
        category: 'Profil',
        ruleType: 'FIRST',
        metric: 'PROFILE_PHOTO_UPLOADED',
        threshold: 1,
        tier: 'BRONZE',
        sortOrder: 90,
    },
    {
        key: 'profile-complete',
        nameCs: 'Kompletní',
        nameEn: 'Complete',
        descriptionCs: 'Vyplnil jsi celý profil. Perfektní!',
        descriptionEn: 'Your profile is 100% complete. Perfect!',
        icon: '✨',
        category: 'Profil',
        ruleType: 'SPECIAL',
        metric: 'PROFILE_COMPLETE',
        threshold: 1,
        tier: 'SILVER',
        sortOrder: 91,
    },
    {
        key: 'theme-changed',
        nameCs: 'Stylista',
        nameEn: 'Stylist',
        descriptionCs: 'Změnil jsi téma aplikace. Každý den nový styl!',
        descriptionEn: 'You changed the app theme. New look, new day!',
        icon: '🎨',
        category: 'Profil',
        ruleType: 'FIRST',
        metric: 'THEME_CHANGED',
        threshold: 1,
        tier: 'BRONZE',
        sortOrder: 92,
    },
    {
        key: 'dark-mode',
        nameCs: 'Noční režim aktivován',
        nameEn: 'Night mode activated',
        descriptionCs: 'Přepnul jsi do tmavého režimu. Oči ti poděkují!',
        descriptionEn: 'You switched to dark mode. Your eyes will thank you!',
        icon: '🌙',
        category: 'Profil',
        ruleType: 'SPECIAL',
        metric: 'DARK_MODE_ENABLED',
        threshold: 1,
        tier: 'BRONZE',
        sortOrder: 93,
    },
    {
        key: 'language-switched',
        nameCs: 'Jazykový přepínač',
        nameEn: 'Language switcher',
        descriptionCs: 'Přepnul jsi jazyk aplikace. Vícejazyčnost je super!',
        descriptionEn: 'You switched the app language. Multilingualism rocks!',
        icon: '🌐',
        category: 'Profil',
        ruleType: 'FIRST',
        metric: 'LANGUAGE_SWITCHED',
        threshold: 1,
        tier: 'BRONZE',
        sortOrder: 94,
    },
    {
        key: 'pwa-installed',
        nameCs: 'App installed',
        nameEn: 'App installed',
        descriptionCs: 'Nainstaloval jsi aplikaci do telefonu. Teď ji máš vždy po ruce!',
        descriptionEn: 'You installed the app on your phone. Always at hand now!',
        icon: '📱',
        category: 'Profil',
        ruleType: 'FIRST',
        metric: 'APP_INSTALLED',
        threshold: 1,
        tier: 'SILVER',
        sortOrder: 95,
    },
    // ── Seasonal & special ────────────────────────────────
    {
        key: 'birthday-activity',
        nameCs: 'Narozeninová hvězda',
        nameEn: 'Birthday star',
        descriptionCs: 'Naplánoval jsi akci na svůj vlastní narozeniny! Paráda!',
        descriptionEn: 'You planned something on your own birthday! Awesome!',
        icon: '🎂',
        category: 'Speciální',
        ruleType: 'SPECIAL',
        metric: 'ACTIVITY_ON_BIRTHDAY',
        threshold: 1,
        tier: 'GOLD',
        sortOrder: 100,
    },
    {
        key: 'new-year-login',
        nameCs: 'Novoroční odhodlání',
        nameEn: 'New Year\'s resolution',
        descriptionCs: 'Přihlásil jsi se 1. ledna. Rok začínáš s přehledem!',
        descriptionEn: 'You logged in on January 1st. Starting the year organized!',
        icon: '🎆',
        category: 'Speciální',
        ruleType: 'SPECIAL',
        metric: 'LOGIN_JAN1',
        threshold: 1,
        tier: 'SILVER',
        sortOrder: 101,
    },
    {
        key: 'summer-holidays-start',
        nameCs: 'Prázdniny začínají!',
        nameEn: 'Summer holidays begin!',
        descriptionCs: 'Byl jsi aktivní první den letních prázdnin. Plánovat se musí!',
        descriptionEn: 'You were active on the first day of summer holidays. Planning matters!',
        icon: '☀️',
        category: 'Speciální',
        ruleType: 'SPECIAL',
        metric: 'ACTIVE_ON_SUMMER_HOLIDAY_START',
        threshold: 1,
        tier: 'BRONZE',
        sortOrder: 102,
    },
    {
        key: 'mikulas',
        nameCs: 'Mikuláš přichází',
        nameEn: 'St. Nicholas is coming',
        descriptionCs: 'Přihlásil ses na Mikuláše (6. 12.). Hodný nebo zlobivý?',
        descriptionEn: 'You logged in on St. Nicholas day (Dec 6). Naughty or nice?',
        icon: '🎅',
        category: 'Speciální',
        ruleType: 'SPECIAL',
        metric: 'LOGIN_DEC6',
        threshold: 1,
        tier: 'BRONZE',
        sortOrder: 103,
    },
    {
        key: 'christmas-event',
        nameCs: 'Štědrý den',
        nameEn: 'Christmas Eve',
        descriptionCs: 'Přidal jsi událost na Štědrý den. Tradice se dodržuje!',
        descriptionEn: 'You added an event on Christmas Eve. Keeping the tradition!',
        icon: '🎄',
        category: 'Speciální',
        ruleType: 'SPECIAL',
        metric: 'EVENT_ON_DEC24',
        threshold: 1,
        tier: 'SILVER',
        sortOrder: 104,
    },
    {
        key: 'vacation-abroad',
        nameCs: 'Světoběžník',
        nameEn: 'World traveler',
        descriptionCs: 'Naplánoval jsi dovolenou v zahraničí. Svet je velký!',
        descriptionEn: 'You planned a vacation abroad. The world is big!',
        icon: '✈️',
        category: 'Speciální',
        ruleType: 'SPECIAL',
        metric: 'VACATION_ABROAD',
        threshold: 1,
        tier: 'GOLD',
        sortOrder: 105,
    },
    {
        key: 'all-five-themes',
        nameCs: 'Módní ikona',
        nameEn: 'Fashion icon',
        descriptionCs: 'Vyzkoušel jsi všech 5 témat aplikace. Styl bez kompromisů!',
        descriptionEn: 'You tried all 5 app themes. Style without compromise!',
        icon: '💅',
        category: 'Speciální',
        ruleType: 'SPECIAL',
        metric: 'ALL_THEMES_TRIED',
        threshold: 5,
        tier: 'GOLD',
        sortOrder: 106,
    },
    {
        key: 'attachment-count-10',
        nameCs: 'Archivář',
        nameEn: 'Archivist',
        descriptionCs: '10 příloh nahráno. Ty nic neztratíš!',
        descriptionEn: '10 attachments uploaded. You never lose anything!',
        icon: '📦',
        category: 'Speciální',
        ruleType: 'COUNT',
        metric: 'ATTACHMENT_UPLOADED',
        threshold: 10,
        tier: 'BRONZE',
        sortOrder: 107,
    },
    {
        key: 'ics-feed-used',
        nameCs: 'Tech wizard',
        nameEn: 'Tech wizard',
        descriptionCs: 'Přihlásil ses k ICS kanálu. Technologický čaroděj!',
        descriptionEn: 'You subscribed to the ICS feed. Tech wizard!',
        icon: '🧙',
        category: 'Speciální',
        ruleType: 'SPECIAL',
        metric: 'ICS_FEED_SUBSCRIBED',
        threshold: 1,
        tier: 'SILVER',
        sortOrder: 108,
    },
    {
        key: 'family-full-house',
        nameCs: 'Celá rodina',
        nameEn: 'Full house',
        descriptionCs: 'Všichni členové rodiny jsou aktivní v kalendáři. Super!',
        descriptionEn: 'All family members are active in the calendar. Awesome!',
        icon: '👨‍👩‍👧‍👦',
        category: 'Speciální',
        ruleType: 'SPECIAL',
        metric: 'ALL_FAMILY_MEMBERS_ACTIVE',
        threshold: 1,
        tier: 'GOLD',
        sortOrder: 109,
    },
    {
        key: 'event-edited-5',
        nameCs: 'Dokonalý detailista',
        nameEn: 'Perfect detailer',
        descriptionCs: '5 událostí opraveno. Přesnost je základ!',
        descriptionEn: '5 events edited. Precision is everything!',
        icon: '✏️',
        category: 'Události',
        ruleType: 'COUNT',
        metric: 'EVENT_EDITED',
        threshold: 5,
        tier: 'BRONZE',
        sortOrder: 30,
    },
    // ── More event badges ──────────────────────────────────
    {
        key: 'event-edited-20',
        nameCs: 'Precizní plánovač',
        nameEn: 'Precise planner',
        descriptionCs: '20 událostí upraveno. Dokonalost přichází s praxí!',
        descriptionEn: '20 events edited. Perfection comes with practice!',
        icon: '🖊️',
        category: 'Události',
        ruleType: 'COUNT',
        metric: 'EVENT_EDITED',
        threshold: 20,
        tier: 'SILVER',
        sortOrder: 31,
    },
    {
        key: 'event-created-50',
        nameCs: 'Organizační génius',
        nameEn: 'Organizational genius',
        descriptionCs: '50 událostí vytvořeno. Skutečný mistr plánování!',
        descriptionEn: '50 events created. A true planning master!',
        icon: '🏆',
        category: 'Události',
        ruleType: 'COUNT',
        metric: 'EVENT_CREATED',
        threshold: 50,
        tier: 'GOLD',
        sortOrder: 25,
    },
    {
        key: 'event-created-100',
        nameCs: 'Legendární organizátor',
        nameEn: 'Legendary organizer',
        descriptionCs: '100 událostí! Jsi legendou rodinného plánování!',
        descriptionEn: '100 events! You are a legend of family planning!',
        icon: '👑',
        category: 'Události',
        ruleType: 'COUNT',
        metric: 'EVENT_CREATED',
        threshold: 100,
        tier: 'GOLD',
        sortOrder: 26,
    },
    // ── Attendance & sports ──────────────────────────────────
    {
        key: 'hockey-20',
        nameCs: 'Hokejový borec',
        nameEn: 'Hockey champion',
        descriptionCs: '20 hokejových tréninků zaznamenaných. Tak to má vypadat!',
        descriptionEn: '20 hockey trainings logged. That\'s how it\'s done!',
        icon: '🏒',
        category: 'Sport',
        ruleType: 'COUNT',
        metric: 'EVENT_CREATED_hokej',
        threshold: 20,
        tier: 'SILVER',
        sortOrder: 51,
    },
    {
        key: 'hockey-50',
        nameCs: 'Budoucí profík',
        nameEn: 'Future pro',
        descriptionCs: '50 hokejových tréninků. Na NHL tě připravujeme!',
        descriptionEn: '50 hockey trainings. We\'re preparing you for the NHL!',
        icon: '🥅',
        category: 'Sport',
        ruleType: 'COUNT',
        metric: 'EVENT_CREATED_hokej',
        threshold: 50,
        tier: 'GOLD',
        sortOrder: 52,
    },
    {
        key: 'swimming-20',
        nameCs: 'Vodní drak',
        nameEn: 'Water dragon',
        descriptionCs: '20 plaveckých tréninků zaznamenaných. Voda tě má ráda!',
        descriptionEn: '20 swimming trainings logged. Water loves you!',
        icon: '🏊',
        category: 'Sport',
        ruleType: 'COUNT',
        metric: 'EVENT_CREATED_plavani',
        threshold: 20,
        tier: 'SILVER',
        sortOrder: 56,
    },
    {
        key: 'swimming-50',
        nameCs: 'Mořský had',
        nameEn: 'Sea serpent',
        descriptionCs: '50 plaveckých tréninků. Ryby tě závidí!',
        descriptionEn: '50 swimming trainings. The fish envy you!',
        icon: '🐟',
        category: 'Sport',
        ruleType: 'COUNT',
        metric: 'EVENT_CREATED_plavani',
        threshold: 50,
        tier: 'GOLD',
        sortOrder: 57,
    },
    // ── Family & social ──────────────────────────────────
    {
        key: 'first-family-event',
        nameCs: 'Rodinná sešlost',
        nameEn: 'Family gathering',
        descriptionCs: 'Vytvořil jsi první rodinnou akci. Začínáme!',
        descriptionEn: 'You created the first family event. Let\'s go!',
        icon: '🏡',
        category: 'Rodina',
        ruleType: 'FIRST',
        metric: 'EVENT_CREATED_rodina',
        threshold: 1,
        tier: 'BRONZE',
        sortOrder: 61,
    },
    {
        key: 'family-events-10',
        nameCs: 'Stmelující element',
        nameEn: 'Binding element',
        descriptionCs: '10 rodinných akcí. Udržuješ rodinu pohromadě!',
        descriptionEn: '10 family events. You keep the family together!',
        icon: '🤗',
        category: 'Rodina',
        ruleType: 'COUNT',
        metric: 'EVENT_CREATED_rodina',
        threshold: 10,
        tier: 'SILVER',
        sortOrder: 62,
    },
    {
        key: 'grandparent-visit-5',
        nameCs: 'Milý vnuk/vnučka',
        nameEn: 'Loving grandchild',
        descriptionCs: '5 návštěv u prarodičů naplánováno. Rodina je základ!',
        descriptionEn: '5 grandparent visits planned. Family is everything!',
        icon: '👴',
        category: 'Rodina',
        ruleType: 'COUNT',
        metric: 'EVENT_CREATED_navsteva-prarodicu',
        threshold: 5,
        tier: 'BRONZE',
        sortOrder: 63,
    },
    // ── School badges ──────────────────────────────────
    {
        key: 'school-term-complete',
        nameCs: 'Pololetí zvládnuto',
        nameEn: 'Term completed',
        descriptionCs: 'Celé pololetí mělo zaznamenané události. Výborně!',
        descriptionEn: 'Whole term had logged events. Excellent!',
        icon: '📚',
        category: 'Škola',
        ruleType: 'COUNT',
        metric: 'EVENT_CREATED_skola',
        threshold: 20,
        tier: 'SILVER',
        sortOrder: 71,
    },
    {
        key: 'school-test-5',
        nameCs: 'Připravený student',
        nameEn: 'Prepared student',
        descriptionCs: '5 testů v kalendáři. Žádné překvapení!',
        descriptionEn: '5 tests in the calendar. No surprises!',
        icon: '📝',
        category: 'Škola',
        ruleType: 'COUNT',
        metric: 'EVENT_CREATED_test-zkouska',
        threshold: 5,
        tier: 'BRONZE',
        sortOrder: 72,
    },
    // ── Login milestones ──────────────────────────────────
    {
        key: 'login-50',
        nameCs: 'Věrný uživatel',
        nameEn: 'Loyal user',
        descriptionCs: '50 přihlášení. Jsi páteří rodiny!',
        descriptionEn: '50 logins. You are the backbone of the family!',
        icon: '💙',
        category: 'Přihlášení',
        ruleType: 'COUNT',
        metric: 'LOGIN',
        threshold: 50,
        tier: 'SILVER',
        sortOrder: 17,
    },
    {
        key: 'login-200',
        nameCs: 'Nezastavitelný',
        nameEn: 'Unstoppable',
        descriptionCs: '200 přihlášení. Jsi neodmyslitelnou součástí aplikace!',
        descriptionEn: '200 logins. You are an irreplaceable part of the app!',
        icon: '🚀',
        category: 'Přihlášení',
        ruleType: 'COUNT',
        metric: 'LOGIN',
        threshold: 200,
        tier: 'GOLD',
        sortOrder: 18,
    },
    {
        key: 'login-streak-21',
        nameCs: 'Tři týdny bez přestávky',
        nameEn: 'Three weeks straight',
        descriptionCs: '21 dní v řadě. Aplikace je tvojí součástí dne!',
        descriptionEn: '21 days in a row. The app is part of your daily routine!',
        icon: '🔥',
        category: 'Přihlášení',
        ruleType: 'STREAK',
        metric: 'LOGIN_STREAK',
        threshold: 21,
        tier: 'GOLD',
        sortOrder: 16,
    },
    // ── Availability & planning ──────────────────────────────────
    {
        key: 'availability-first',
        nameCs: 'Dostupný opatrovník',
        nameEn: 'Available guardian',
        descriptionCs: 'Poprvé jsi nastavil svou dostupnost. Díky za zodpovědnost!',
        descriptionEn: 'You set your availability for the first time. Thanks for being responsible!',
        icon: '📍',
        category: 'Dostupnost',
        ruleType: 'FIRST',
        metric: 'AVAILABILITY_SET',
        threshold: 1,
        tier: 'BRONZE',
        sortOrder: 81,
    },
    {
        key: 'availability-10',
        nameCs: 'Spolehlivý opatrovník',
        nameEn: 'Reliable guardian',
        descriptionCs: '10x jsi nastavil dostupnost. Na tebe je spoleh!',
        descriptionEn: '10 times you set your availability. You can be counted on!',
        icon: '🛡️',
        category: 'Dostupnost',
        ruleType: 'COUNT',
        metric: 'AVAILABILITY_SET',
        threshold: 10,
        tier: 'SILVER',
        sortOrder: 82,
    },
    {
        key: 'availability-30',
        nameCs: 'Pilíř rodiny',
        nameEn: 'Family pillar',
        descriptionCs: '30x dostupnost nastavena. Bez tebe by to nešlo!',
        descriptionEn: '30 times availability set. It couldn\'t work without you!',
        icon: '🏛️',
        category: 'Dostupnost',
        ruleType: 'COUNT',
        metric: 'AVAILABILITY_SET',
        threshold: 30,
        tier: 'GOLD',
        sortOrder: 83,
    },
    // ── Profile & personalization ──────────────────────────────────
    {
        key: 'language-switch',
        nameCs: 'Polyglot',
        nameEn: 'Polyglot',
        descriptionCs: 'Přepnul jsi jazyk aplikace. Mluvíš více jazyky!',
        descriptionEn: 'You switched the app language. You speak multiple languages!',
        icon: '🌐',
        category: 'Profil',
        ruleType: 'SPECIAL',
        metric: 'LANGUAGE_SWITCHED',
        threshold: 1,
        tier: 'BRONZE',
        sortOrder: 92,
    },
    {
        key: 'theme-changer-5',
        nameCs: 'Módní experimentátor',
        nameEn: 'Fashion experimenter',
        descriptionCs: '5x jsi změnil motiv. Styl se neustále vyvíjí!',
        descriptionEn: '5 times you changed the theme. Style is constantly evolving!',
        icon: '🎨',
        category: 'Profil',
        ruleType: 'COUNT',
        metric: 'THEME_CHANGED',
        threshold: 5,
        tier: 'BRONZE',
        sortOrder: 93,
    },
    {
        key: 'pwa-user',
        nameCs: 'Nainstalovaný uživatel',
        nameEn: 'Installed user',
        descriptionCs: 'Nainstaluješ aplikaci jako PWA. Máš ji vždy po ruce!',
        descriptionEn: 'You installed the app as a PWA. Always at hand!',
        icon: '📲',
        category: 'Profil',
        ruleType: 'SPECIAL',
        metric: 'APP_INSTALLED',
        threshold: 1,
        tier: 'SILVER',
        sortOrder: 94,
    },
    // ── Proposals & approvals ──────────────────────────────────
    {
        key: 'proposal-first',
        nameCs: 'Odvážný plánovač',
        nameEn: 'Bold planner',
        descriptionCs: 'Poprvé jsi navrhl událost. Odvaha se cení!',
        descriptionEn: 'You proposed an event for the first time. Courage is valued!',
        icon: '💡',
        category: 'Návrhy',
        ruleType: 'FIRST',
        metric: 'PROPOSAL_SUBMITTED',
        threshold: 1,
        tier: 'BRONZE',
        sortOrder: 41,
    },
    {
        key: 'proposal-5',
        nameCs: 'Návrhy na porad',
        nameEn: 'Serial proposer',
        descriptionCs: '5 návrhů události. Stále přicházíš s nápady!',
        descriptionEn: '5 event proposals. You keep coming up with ideas!',
        icon: '🗳️',
        category: 'Návrhy',
        ruleType: 'COUNT',
        metric: 'PROPOSAL_SUBMITTED',
        threshold: 5,
        tier: 'SILVER',
        sortOrder: 42,
    },
    {
        key: 'proposal-approved-5',
        nameCs: 'Schválený vizionář',
        nameEn: 'Approved visionary',
        descriptionCs: '5 návrhů schváleno. Rodiče ti věří!',
        descriptionEn: '5 proposals approved. Parents trust you!',
        icon: '✅',
        category: 'Návrhy',
        ruleType: 'COUNT',
        metric: 'PROPOSAL_APPROVED',
        threshold: 5,
        tier: 'SILVER',
        sortOrder: 43,
    },
    // ── Attachment badges ──────────────────────────────────
    {
        key: 'attachment-first',
        nameCs: 'Dokumentátor',
        nameEn: 'Documenter',
        descriptionCs: 'Poprvé jsi nahrál přílohu. Máš důkazy!',
        descriptionEn: 'You uploaded an attachment for the first time. You have proof!',
        icon: '📎',
        category: 'Přílohy',
        ruleType: 'FIRST',
        metric: 'ATTACHMENT_UPLOADED',
        threshold: 1,
        tier: 'BRONZE',
        sortOrder: 111,
    },
    {
        key: 'attachment-25',
        nameCs: 'Kronikář rodiny',
        nameEn: 'Family chronicler',
        descriptionCs: '25 příloh nahráno. Tvoříš rodinný archiv!',
        descriptionEn: '25 attachments uploaded. You are creating a family archive!',
        icon: '📚',
        category: 'Přílohy',
        ruleType: 'COUNT',
        metric: 'ATTACHMENT_UPLOADED',
        threshold: 25,
        tier: 'SILVER',
        sortOrder: 112,
    },
    {
        key: 'attachment-50',
        nameCs: 'Velký archivář',
        nameEn: 'Great archivist',
        descriptionCs: '50 příloh nahráno. Nás nic nepřekvapí!',
        descriptionEn: '50 attachments uploaded. Nothing will surprise us!',
        icon: '🗄️',
        category: 'Přílohy',
        ruleType: 'COUNT',
        metric: 'ATTACHMENT_UPLOADED',
        threshold: 50,
        tier: 'GOLD',
        sortOrder: 113,
    },
    // ── Vacation & trips ──────────────────────────────────
    {
        key: 'vacation-first',
        nameCs: 'Cestovatel',
        nameEn: 'Traveler',
        descriptionCs: 'První dovolená naplánována. Jede se!',
        descriptionEn: 'First vacation planned. Let\'s go!',
        icon: '🌴',
        category: 'Cestování',
        ruleType: 'FIRST',
        metric: 'EVENT_CREATED_dovolena',
        threshold: 1,
        tier: 'BRONZE',
        sortOrder: 121,
    },
    {
        key: 'vacation-5',
        nameCs: 'Zkušený cestovatel',
        nameEn: 'Experienced traveler',
        descriptionCs: '5 dovolených zaznamenaných. Žiješ naplno!',
        descriptionEn: '5 vacations logged. You live life to the fullest!',
        icon: '🗺️',
        category: 'Cestování',
        ruleType: 'COUNT',
        metric: 'EVENT_CREATED_dovolena',
        threshold: 5,
        tier: 'SILVER',
        sortOrder: 122,
    },
    {
        key: 'roadtrip-first',
        nameCs: 'Dobrodružný duch',
        nameEn: 'Adventurous spirit',
        descriptionCs: 'První výlet naplánován. Cesta je cíl!',
        descriptionEn: 'First road trip planned. The journey is the goal!',
        icon: '🚗',
        category: 'Cestování',
        ruleType: 'FIRST',
        metric: 'EVENT_CREATED_vylet',
        threshold: 1,
        tier: 'BRONZE',
        sortOrder: 123,
    },
    {
        key: 'camp-first',
        nameCs: 'Táborník',
        nameEn: 'Camper',
        descriptionCs: 'První tábor v kalendáři. Dobrodružství čeká!',
        descriptionEn: 'First camp in the calendar. Adventure awaits!',
        icon: '⛺',
        category: 'Cestování',
        ruleType: 'FIRST',
        metric: 'EVENT_CREATED_tabor',
        threshold: 1,
        tier: 'BRONZE',
        sortOrder: 124,
    },
];
//# sourceMappingURL=badges.js.map