export interface EventTypeSeed {
  slug: string;
  nameCs: string;
  nameEn: string;
  icon: string;
  color: string;
  groupCs: string;
  groupEn: string;
  defaultDurationMinutes: number;
  defaultReminderMinutes: number;
  sortOrder: number;
}

export const EVENT_TYPES_SEED: EventTypeSeed[] = [
  // ── Hockey (9yo – Jakub) ──────────────────────────────
  {
    slug: 'hokej-trening',
    nameCs: 'Trénink hokej',
    nameEn: 'Hockey training',
    icon: '🏒',
    color: '#64748b',
    groupCs: 'Lední hokej',
    groupEn: 'Ice Hockey',
    defaultDurationMinutes: 90,
    defaultReminderMinutes: 60,
    sortOrder: 10,
  },
  {
    slug: 'hokej-zapas',
    nameCs: 'Zápas hokej',
    nameEn: 'Hockey match',
    icon: '🏆',
    color: '#1e40af',
    groupCs: 'Lední hokej',
    groupEn: 'Ice Hockey',
    defaultDurationMinutes: 120,
    defaultReminderMinutes: 120,
    sortOrder: 11,
  },
  {
    slug: 'hokej-turnaj',
    nameCs: 'Turnaj hokej',
    nameEn: 'Hockey tournament',
    icon: '🥇',
    color: '#c2410c',
    groupCs: 'Lední hokej',
    groupEn: 'Ice Hockey',
    defaultDurationMinutes: 480,
    defaultReminderMinutes: 1440,
    sortOrder: 12,
  },
  {
    slug: 'hokej-kemp',
    nameCs: 'Hokejový kemp',
    nameEn: 'Hockey camp',
    icon: '⛸️',
    color: '#0f766e',
    groupCs: 'Lední hokej',
    groupEn: 'Ice Hockey',
    defaultDurationMinutes: 480,
    defaultReminderMinutes: 1440,
    sortOrder: 13,
  },
  {
    slug: 'hokej-soustredeni',
    nameCs: 'Soustředění hokej',
    nameEn: 'Hockey camp/retreat',
    icon: '🏕️',
    color: '#4338ca',
    groupCs: 'Lední hokej',
    groupEn: 'Ice Hockey',
    defaultDurationMinutes: 1440,
    defaultReminderMinutes: 1440,
    sortOrder: 14,
  },
  {
    slug: 'hokej-servis',
    nameCs: 'Servis výstroje',
    nameEn: 'Equipment service',
    icon: '🔧',
    color: '#78716c',
    groupCs: 'Lední hokej',
    groupEn: 'Ice Hockey',
    defaultDurationMinutes: 60,
    defaultReminderMinutes: 60,
    sortOrder: 15,
  },

  // ── Swimming (11yo – Tereza) ──────────────────────────
  {
    slug: 'plavani-trening',
    nameCs: 'Trénink plavání',
    nameEn: 'Swimming training',
    icon: '🏊',
    color: '#0ea5e9',
    groupCs: 'Plavání',
    groupEn: 'Swimming',
    defaultDurationMinutes: 90,
    defaultReminderMinutes: 60,
    sortOrder: 20,
  },
  {
    slug: 'plavani-zavody',
    nameCs: 'Závody plavání',
    nameEn: 'Swimming race',
    icon: '🥈',
    color: '#0284c7',
    groupCs: 'Plavání',
    groupEn: 'Swimming',
    defaultDurationMinutes: 180,
    defaultReminderMinutes: 120,
    sortOrder: 21,
  },
  {
    slug: 'plavani-soustredeni',
    nameCs: 'Plavecké soustředění',
    nameEn: 'Swimming retreat',
    icon: '🌊',
    color: '#0891b2',
    groupCs: 'Plavání',
    groupEn: 'Swimming',
    defaultDurationMinutes: 1440,
    defaultReminderMinutes: 1440,
    sortOrder: 22,
  },
  {
    slug: 'plavani-kondice',
    nameCs: 'Kondiční trénink',
    nameEn: 'Conditioning training',
    icon: '💪',
    color: '#06b6d4',
    groupCs: 'Plavání',
    groupEn: 'Swimming',
    defaultDurationMinutes: 60,
    defaultReminderMinutes: 60,
    sortOrder: 23,
  },

  // ── School ────────────────────────────────────────────
  {
    slug: 'skola-vyucovani',
    nameCs: 'Vyučování',
    nameEn: 'School',
    icon: '🎒',
    color: '#16a34a',
    groupCs: 'Škola',
    groupEn: 'School',
    defaultDurationMinutes: 360,
    defaultReminderMinutes: 60,
    sortOrder: 30,
  },
  {
    slug: 'skola-test',
    nameCs: 'Test / písemka',
    nameEn: 'Test / exam',
    icon: '📝',
    color: '#dc2626',
    groupCs: 'Škola',
    groupEn: 'School',
    defaultDurationMinutes: 60,
    defaultReminderMinutes: 1440,
    sortOrder: 31,
  },
  {
    slug: 'skola-ukol',
    nameCs: 'Domácí úkol — termín',
    nameEn: 'Homework deadline',
    icon: '📚',
    color: '#ca8a04',
    groupCs: 'Škola',
    groupEn: 'School',
    defaultDurationMinutes: 30,
    defaultReminderMinutes: 1440,
    sortOrder: 32,
  },
  {
    slug: 'skola-schuze',
    nameCs: 'Třídní schůzky',
    nameEn: 'Parent-teacher meeting',
    icon: '👨‍👩‍👧',
    color: '#7c3aed',
    groupCs: 'Škola',
    groupEn: 'School',
    defaultDurationMinutes: 90,
    defaultReminderMinutes: 1440,
    sortOrder: 33,
  },
  {
    slug: 'skola-akademie',
    nameCs: 'Školní besídka / akademie',
    nameEn: 'School show',
    icon: '🎭',
    color: '#db2777',
    groupCs: 'Škola',
    groupEn: 'School',
    defaultDurationMinutes: 120,
    defaultReminderMinutes: 1440,
    sortOrder: 34,
  },
  {
    slug: 'skola-vylet',
    nameCs: 'Výlet se školou',
    nameEn: 'School trip',
    icon: '🚌',
    color: '#ea580c',
    groupCs: 'Škola',
    groupEn: 'School',
    defaultDurationMinutes: 480,
    defaultReminderMinutes: 1440,
    sortOrder: 35,
  },
  {
    slug: 'skola-volno',
    nameCs: 'Ředitelské volno',
    nameEn: "Principal's day off",
    icon: '🎉',
    color: '#65a30d',
    groupCs: 'Škola',
    groupEn: 'School',
    defaultDurationMinutes: 1440,
    defaultReminderMinutes: 1440,
    sortOrder: 36,
  },
  {
    slug: 'skola-krouzek',
    nameCs: 'Kroužek',
    nameEn: 'After-school club',
    icon: '🎨',
    color: '#9333ea',
    groupCs: 'Škola',
    groupEn: 'School',
    defaultDurationMinutes: 90,
    defaultReminderMinutes: 60,
    sortOrder: 37,
  },

  // ── School subjects (for schedule/rozvrh) ────────────
  {
    slug: 'predmet-matematika',
    nameCs: 'Matematika',
    nameEn: 'Math',
    icon: '🔢',
    color: '#2563eb',
    groupCs: 'Předměty',
    groupEn: 'Subjects',
    defaultDurationMinutes: 45,
    defaultReminderMinutes: 0,
    sortOrder: 38,
  },
  {
    slug: 'predmet-cestina',
    nameCs: 'Čeština',
    nameEn: 'Czech',
    icon: '📖',
    color: '#16a34a',
    groupCs: 'Předměty',
    groupEn: 'Subjects',
    defaultDurationMinutes: 45,
    defaultReminderMinutes: 0,
    sortOrder: 39,
  },
  {
    slug: 'predmet-anglictina',
    nameCs: 'Angličtina',
    nameEn: 'English',
    icon: '🇬🇧',
    color: '#dc2626',
    groupCs: 'Předměty',
    groupEn: 'Subjects',
    defaultDurationMinutes: 45,
    defaultReminderMinutes: 0,
    sortOrder: 40,
  },
  {
    slug: 'predmet-prirodoveda',
    nameCs: 'Přírodověda',
    nameEn: 'Science',
    icon: '🔬',
    color: '#059669',
    groupCs: 'Předměty',
    groupEn: 'Subjects',
    defaultDurationMinutes: 45,
    defaultReminderMinutes: 0,
    sortOrder: 41,
  },
  {
    slug: 'predmet-dejepiszeuvod',
    nameCs: 'Dějepis / Vlastivěda',
    nameEn: 'History / Civics',
    icon: '🏛️',
    color: '#92400e',
    groupCs: 'Předměty',
    groupEn: 'Subjects',
    defaultDurationMinutes: 45,
    defaultReminderMinutes: 0,
    sortOrder: 42,
  },
  {
    slug: 'predmet-tv',
    nameCs: 'Tělesná výchova',
    nameEn: 'PE',
    icon: '🏃',
    color: '#7c3aed',
    groupCs: 'Předměty',
    groupEn: 'Subjects',
    defaultDurationMinutes: 45,
    defaultReminderMinutes: 0,
    sortOrder: 43,
  },
  {
    slug: 'predmet-vv',
    nameCs: 'Výtvarná výchova',
    nameEn: 'Art',
    icon: '🎨',
    color: '#db2777',
    groupCs: 'Předměty',
    groupEn: 'Subjects',
    defaultDurationMinutes: 45,
    defaultReminderMinutes: 0,
    sortOrder: 44,
  },
  {
    slug: 'predmet-hudebni',
    nameCs: 'Hudební výchova',
    nameEn: 'Music',
    icon: '🎵',
    color: '#6d28d9',
    groupCs: 'Předměty',
    groupEn: 'Subjects',
    defaultDurationMinutes: 45,
    defaultReminderMinutes: 0,
    sortOrder: 45,
  },
  {
    slug: 'predmet-informatika',
    nameCs: 'Informatika',
    nameEn: 'Computer Science',
    icon: '💻',
    color: '#0891b2',
    groupCs: 'Předměty',
    groupEn: 'Subjects',
    defaultDurationMinutes: 45,
    defaultReminderMinutes: 0,
    sortOrder: 46,
  },
  {
    slug: 'predmet-nemcina',
    nameCs: 'Němčina',
    nameEn: 'German',
    icon: '🇩🇪',
    color: '#d97706',
    groupCs: 'Předměty',
    groupEn: 'Subjects',
    defaultDurationMinutes: 45,
    defaultReminderMinutes: 0,
    sortOrder: 47,
  },

  // ── Lessons ───────────────────────────────────────────
  {
    slug: 'lekce-hudba',
    nameCs: 'Hudební škola',
    nameEn: 'Music school',
    icon: '🎵',
    color: '#8b5cf6',
    groupCs: 'Lekce',
    groupEn: 'Lessons',
    defaultDurationMinutes: 60,
    defaultReminderMinutes: 60,
    sortOrder: 40,
  },
  {
    slug: 'lekce-jazyky',
    nameCs: 'Jazykový kroužek',
    nameEn: 'Language class',
    icon: '🌍',
    color: '#06b6d4',
    groupCs: 'Lekce',
    groupEn: 'Lessons',
    defaultDurationMinutes: 60,
    defaultReminderMinutes: 60,
    sortOrder: 41,
  },
  {
    slug: 'lekce-doucovani',
    nameCs: 'Doučování',
    nameEn: 'Tutoring',
    icon: '🧮',
    color: '#f59e0b',
    groupCs: 'Lekce',
    groupEn: 'Lessons',
    defaultDurationMinutes: 60,
    defaultReminderMinutes: 30,
    sortOrder: 42,
  },

  // ── Family & Travel ───────────────────────────────────
  {
    slug: 'rodina-vylet',
    nameCs: 'Rodinný výlet',
    nameEn: 'Family trip',
    icon: '🗺️',
    color: '#f97316',
    groupCs: 'Rodina & cestování',
    groupEn: 'Family & Travel',
    defaultDurationMinutes: 480,
    defaultReminderMinutes: 1440,
    sortOrder: 50,
  },
  {
    slug: 'rodina-roadtrip',
    nameCs: 'Roadtrip',
    nameEn: 'Road trip',
    icon: '🚗',
    color: '#0f172a',
    groupCs: 'Rodina & cestování',
    groupEn: 'Family & Travel',
    defaultDurationMinutes: 1440,
    defaultReminderMinutes: 1440,
    sortOrder: 51,
  },
  {
    slug: 'rodina-dovolena',
    nameCs: 'Dovolená',
    nameEn: 'Vacation',
    icon: '🏖️',
    color: '#f59e0b',
    groupCs: 'Rodina & cestování',
    groupEn: 'Family & Travel',
    defaultDurationMinutes: 10080,
    defaultReminderMinutes: 2880,
    sortOrder: 52,
  },
  {
    slug: 'rodina-babicka',
    nameCs: 'Pobyt u prarodičů',
    nameEn: 'Stay at grandparents',
    icon: '🏡',
    color: '#84cc16',
    groupCs: 'Rodina & cestování',
    groupEn: 'Family & Travel',
    defaultDurationMinutes: 1440,
    defaultReminderMinutes: 1440,
    sortOrder: 53,
  },
  {
    slug: 'rodina-navsteva',
    nameCs: 'Návštěva',
    nameEn: 'Visit',
    icon: '👋',
    color: '#ec4899',
    groupCs: 'Rodina & cestování',
    groupEn: 'Family & Travel',
    defaultDurationMinutes: 180,
    defaultReminderMinutes: 60,
    sortOrder: 54,
  },
  {
    slug: 'rodina-oslava',
    nameCs: 'Oslava / narozeniny',
    nameEn: 'Celebration / birthday',
    icon: '🎂',
    color: '#a855f7',
    groupCs: 'Rodina & cestování',
    groupEn: 'Family & Travel',
    defaultDurationMinutes: 180,
    defaultReminderMinutes: 1440,
    sortOrder: 55,
  },
  {
    slug: 'rodina-svatek',
    nameCs: 'Svátek',
    nameEn: 'Name day',
    icon: '🌸',
    color: '#f43f5e',
    groupCs: 'Rodina & cestování',
    groupEn: 'Family & Travel',
    defaultDurationMinutes: 60,
    defaultReminderMinutes: 1440,
    sortOrder: 56,
  },

  // ── Camps ─────────────────────────────────────────────
  {
    slug: 'tabor-letni',
    nameCs: 'Letní tábor',
    nameEn: 'Summer camp',
    icon: '⛺',
    color: '#22c55e',
    groupCs: 'Tábory',
    groupEn: 'Camps',
    defaultDurationMinutes: 10080,
    defaultReminderMinutes: 4320,
    sortOrder: 60,
  },
  {
    slug: 'tabor-primestsky',
    nameCs: 'Příměstský tábor',
    nameEn: 'Day camp',
    icon: '🌄',
    color: '#84cc16',
    groupCs: 'Tábory',
    groupEn: 'Camps',
    defaultDurationMinutes: 1440,
    defaultReminderMinutes: 1440,
    sortOrder: 61,
  },
  {
    slug: 'tabor-zimni',
    nameCs: 'Zimní tábor / lyžák',
    nameEn: 'Winter camp / ski trip',
    icon: '⛷️',
    color: '#38bdf8',
    groupCs: 'Tábory',
    groupEn: 'Camps',
    defaultDurationMinutes: 10080,
    defaultReminderMinutes: 4320,
    sortOrder: 62,
  },

  // ── Health & Admin ────────────────────────────────────
  {
    slug: 'zdravi-lekar',
    nameCs: 'Lékař / zubař',
    nameEn: 'Doctor / dentist',
    icon: '🩺',
    color: '#ef4444',
    groupCs: 'Zdraví & administrativa',
    groupEn: 'Health & Admin',
    defaultDurationMinutes: 60,
    defaultReminderMinutes: 1440,
    sortOrder: 70,
  },
  {
    slug: 'zdravi-ockovani',
    nameCs: 'Očkování',
    nameEn: 'Vaccination',
    icon: '💉',
    color: '#f87171',
    groupCs: 'Zdraví & administrativa',
    groupEn: 'Health & Admin',
    defaultDurationMinutes: 30,
    defaultReminderMinutes: 1440,
    sortOrder: 71,
  },
  {
    slug: 'admin-urad',
    nameCs: 'Úřad / administrativa',
    nameEn: 'Official business',
    icon: '🏛️',
    color: '#94a3b8',
    groupCs: 'Zdraví & administrativa',
    groupEn: 'Health & Admin',
    defaultDurationMinutes: 60,
    defaultReminderMinutes: 1440,
    sortOrder: 72,
  },

  // ── Other ─────────────────────────────────────────────
  {
    slug: 'ostatni',
    nameCs: 'Ostatní',
    nameEn: 'Other',
    icon: '📌',
    color: '#a3a3a3',
    groupCs: 'Ostatní',
    groupEn: 'Other',
    defaultDurationMinutes: 60,
    defaultReminderMinutes: 60,
    sortOrder: 99,
  },
];
